### ISSUE TITLE
travis.ci

### ISSUE THREAD

**Issue by 4cecoder** [Byte-Cats/microman#32]
integrations!!! YES MORE!!!!

**Comment by GNRain** [comment]
Travis.Ci has only two available options of being used :

1. On Cloud with various billing plans.
2. On-premises

![image](https://user-images.githubusercontent.com/55233091/196285277-1942500a-9b49-4587-99ed-3a995187fce4.png)

I happened to find an affiliation between GitHub and Travis.CI but it is no longer available (Started in 2014 and discontinued at a later date)

This is a screenshot of me trying to build a pipeline with the GitHub Student Pack Free Plan.

![image](https://user-images.githubusercontent.com/55233091/196285791-679aa8e8-b93d-4ace-bbae-6f6ab613be39.png)

It simply doesn't work.

Looking through the [documentation](https://docs.travis-ci.com/user/tutorial/) furthermore if I could find any means of local installation, I didn't find any lead.

![image](https://user-images.githubusercontent.com/55233091/196286791-226b6da2-9a4f-44e8-8649-84fa0a5a0e8f.png)


I have labeled this issue as "Invalid" and "Wontfix" for my inability to integrate Travis.CI at this moment.

**Comment by 4cecoder** [comment]
https://blog.markvincze.com/setting-up-a-travis-ci-pipeline-for-golang/

**Comment by 4cecoder** [comment]
will fix

please follow the directions and apply the research that you have done and add it to a readme
`docs/travis-cl.md`

**Comment by 4cecoder** [comment]
i've updated a temporary travis.yml based on the article above
